replicaCount: 1

image:
  repository: depnonprodregistry.azurecr.io/eframe-services/dev/graphql-apollo-starter
  tag: "__latest__"
  imagePullSecret: acrsecret

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
